### ISSUE TITLE
Instructions on how to deploy Smart Contracts as Docker Container...

### ISSUE THREAD

**Issue by marcellodesales** [dfinity/icp-dev-env#2]
# Single Container API-first

Are there how-to tutorials on how to deploy examples?

* Stateless API? With possible instructions on DNS with ICP
  * How can I replace Web2 AWS ECS (Container as a Service) with ICP 
  * How can I replace Web2 AWS Lambda (Function as a Service) with ICP
* Statefull API? With possible storage options with ICP
  * How can I replace Web2 Database Service with ICP

I'm looking for a way to solve the problem of containers running in satellites and terminals...

# Single Container Static Content

* Web2 content? How can I deploy a simple content that's Web2 Addressable (DNS with ICP)
  * How can I replace Web2 AWS S3 

# Goal 

* Build a Web2 Kubernetes Cluster of containers running the ICP protocol 
* Be able to translate the world of AWS/AZURE/GCP Kubernetes in a Blockchain format that's Developer friendly 
  * Rust is a big deal
  * So is Golang and other languages
  * Run smart contracts behind a gRPC protocol to bridge between Web2/Web3

**Comment by fxgst** [comment]
Hi @marcellodesales, thanks for your input.
This repo aims to provide new developers a one-click development environment to get started developing canisters on the IC; it's not meant to facilitate switching from AWS to ICP, if I understand your idea correctly.
I'd suggest you propose your idea on the [Internet Computer Forum](https://forum.dfinity.org/), where you can reach a broader audience!
